language: go
go:
- 1.8
install:
- go vet ./...
- cd client && go build . && cd ..
- cd server && go build . && cd ..
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FBepQsPkBXBbYJNKhQeTl1uHpNVdEg2jeAxxVfFSVz/Qxv+W6oQtmEOc8UeMikRRY3dhehgtdzwv/7LeWesrjY0I3KnmfwZxbU1EiG+Hp1i41J4aT2tSjMqqZYqfBwbBbwOYcnDxx6XXjRVD/YtLxLEprZbywcwShVD3hAtSGctxPEB86hPCZyqApJR+UqjxmxOFHWjRDYpgs4hYZ3B66ytIsdJy3aMwuC2woOmXHyvpzlw2SAZblZorIBOhk3f+kiisMRQGsbdeQ5dxbPMRM00Qgq5lSibibzW+As3fofJRh0QDO+lg1d/VyGEbtDLR0+2jnkaJfs0guBZuOqP5XjtL8ovaRCsQmbEUSfg0rpZ+YZstYjaiXMdkL3VeZC+tP8PSduqyi8mTA9wVNSS28rNCPBXIe6mt+WSJeglJXFbBik0gYj8Jar7lVVjb1TH1efyGcDCHf8r+0uDqYkrQMUCYTGbyRijJRbrk1AjS7QEoPPiKr1elajCIDe9GPZc6jg+wowAfcseZHj94+v7SH+NwiXMsRthnrZQrqYZ7MSFeJtRc6+nogWo3QMNuisBIIYnlghqpasvaaXqMKi5/H+r6fUGYARohfsYuY2WapG2heo7+ABZEDpmNJ7EP/D+vEnzYg41vxTfj37hqlfaNbCzHPePSh5s2BhGLKkzPrP4=
  file: 
    - server/server
    - client/client
  overwrite: true
  on:
    repo: meyskens/x-www-browser-forward
    branch: "master"
    tags: true
